services:
  web:
    image: nginx:alpine
    ports:
      - "5173:5173"
    volumes:
      - ./dist:/usr/share/nginx/html/wayrapuka
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
