name: wayrapuka

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    secrets: inherit
    if: github.ref == 'refs/heads/main'
    uses: markmorcos/infrastructure/.github/workflows/deploy-app.yaml@main
    with:
      deployment-key: wayrapuka-deployment-key
      deployment-config: infrastructure.yaml
      deployment-version: ${{ github.sha }}
